"""Initial schema

Revision ID: 13f4d7cbcd21
Revises: 
Create Date: 2026-01-19 04:53:51.028649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '13f4d7cbcd21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('org_type', sa.String(length=100), nullable=True),
    sa.Column('focus_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_is_verified'), 'organizations', ['is_verified'], unique=False)
    op.create_index(op.f('ix_organizations_org_type'), 'organizations', ['org_type'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('start_datetime', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('end_datetime', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=255), nullable=True),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('location_url', sa.String(length=500), nullable=True),
    sa.Column('registration_url', sa.String(length=500), nullable=True),
    sa.Column('registration_required', sa.Boolean(), nullable=False),
    sa.Column('max_attendees', sa.Integer(), nullable=True),
    sa.Column('current_attendees', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_organization_id'), 'events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_events_start_datetime'), 'events', ['start_datetime'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('match_explanation', sa.Text(), nullable=True),
    sa.Column('complementarity_score', sa.Integer(), nullable=True),
    sa.Column('stage_alignment_score', sa.Integer(), nullable=True),
    sa.Column('commitment_alignment_score', sa.Integer(), nullable=True),
    sa.Column('working_style_score', sa.Integer(), nullable=True),
    sa.Column('location_fit_score', sa.Integer(), nullable=True),
    sa.Column('intent_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('intro_requested_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('intro_accepted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_match_score'), 'matches', ['match_score'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_target_user_id'), 'matches', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_matches_user_id'), 'matches', ['user_id'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('news_type', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_is_published'), 'news', ['is_published'], unique=False)
    op.create_index(op.f('ix_news_news_type'), 'news', ['news_type'], unique=False)
    op.create_index(op.f('ix_news_published_at'), 'news', ['published_at'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_organization')
    )
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('stage_eligibility', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location_eligibility', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('other_eligibility', sa.Text(), nullable=True),
    sa.Column('amount_min', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('amount_max', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('application_url', sa.String(length=500), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_category'), 'resources', ['category'], unique=False)
    op.create_index(op.f('ix_resources_organization_id'), 'resources', ['organization_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_match_id'), 'messages', ['match_id'], unique=False)
    op.create_index(op.f('ix_messages_recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.Column('reported_user_id', sa.UUID(), nullable=True),
    sa.Column('reported_org_id', sa.UUID(), nullable=True),
    sa.Column('reported_resource_id', sa.UUID(), nullable=True),
    sa.Column('reported_event_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reported_event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('user_event_rsvps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('rsvp_status', sa.String(length=50), nullable=False),
    sa.Column('rsvp_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_user_event_rsvp')
    )
    op.create_index(op.f('ix_user_event_rsvps_event_id'), 'user_event_rsvps', ['event_id'], unique=False)
    op.create_index(op.f('ix_user_event_rsvps_user_id'), 'user_event_rsvps', ['user_id'], unique=False)
    op.create_table('user_saved_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('saved_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resource_id', name='uq_user_saved_resource')
    )
    op.create_index(op.f('ix_user_saved_resources_resource_id'), 'user_saved_resources', ['resource_id'], unique=False)
    op.create_index(op.f('ix_user_saved_resources_user_id'), 'user_saved_resources', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_saved_resources_user_id'), table_name='user_saved_resources')
    op.drop_index(op.f('ix_user_saved_resources_resource_id'), table_name='user_saved_resources')
    op.drop_table('user_saved_resources')
    op.drop_index(op.f('ix_user_event_rsvps_user_id'), table_name='user_event_rsvps')
    op.drop_index(op.f('ix_user_event_rsvps_event_id'), table_name='user_event_rsvps')
    op.drop_table('user_event_rsvps')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_match_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_resources_organization_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_category'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_news_published_at'), table_name='news')
    op.drop_index(op.f('ix_news_news_type'), table_name='news')
    op.drop_index(op.f('ix_news_is_published'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_matches_user_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_target_user_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_score'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_events_start_datetime'), table_name='events')
    op.drop_index(op.f('ix_events_organization_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_org_type'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_verified'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
