"""Add onboarding fields to User model

Revision ID: d5d6bb795c55
Revises: 13f4d7cbcd21
Create Date: 2026-01-19 05:11:12.712033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd5d6bb795c55'
down_revision: Union[str, None] = '13f4d7cbcd21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_intent', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('stage_preference', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('commitment', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('working_style', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('communication_preference', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('previous_startups', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('github_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('portfolio_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'portfolio_url')
    op.drop_column('users', 'github_url')
    op.drop_column('users', 'previous_startups')
    op.drop_column('users', 'experience_years')
    op.drop_column('users', 'communication_preference')
    op.drop_column('users', 'working_style')
    op.drop_column('users', 'location')
    op.drop_column('users', 'commitment')
    op.drop_column('users', 'stage_preference')
    op.drop_column('users', 'role_intent')
    # ### end Alembic commands ###
